apiVersion: v1
kind: Service
metadata:
  name: mongo-external-service
spec:
  selector:
    app: mongo-express
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30000 # should be between 30000 - 32767
      protocol: TCP
