apiVersion: v1
kind: Service
metadata:
  name: mongo-internal-service
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017 #should match the container port
      protocol: TCP
